import * as dom from "../lib/dom";
dom.importCss({
	/* THIS THEME WAS AUTOGENERATED BY Theme.tmpl.css (UUID: ") */
".ace-katzenmilch .ace_gutter,.ace-katzenmilch .ace_gutter": {
	backgroundColor: "#e8e8e8",
	textColor:"#333",
},

".ace-katzenmilch .ace_print-margin": {
	width: 1,
	backgroundColor: "#e8e8e8",
},

".ace-katzenmilch": {
	backgroundColor: "#f3f2f3",
	textColor:"rgba(15, 0, 9, 1.0)",
},

".ace-katzenmilch .ace_cursor": {
	borderLeft: "2 #100011",
},

".ace-katzenmilch .ace_overwrite-cursors .ace_cursor": {
	borderLeftWidth: 0,
	borderBottom: "1 #100011",
},

".ace-katzenmilch .ace_marker-layer .ace_selection": {
	backgroundColor: "rgba(100, 5, 208, 0.27)",
},

".ace-katzenmilch.ace_multiselect .ace_selection.ace_start": {
	boxShadow: "0 0 3 #f3f2f3",
},

".ace-katzenmilch .ace_marker-layer .ace_step": {
	backgroundColor: "rgb(198, 219, 174)",
},

".ace-katzenmilch .ace_marker-layer .ace_bracket": {
	margin: [-1, 0, 0, -1],
	border: "1 rgba(0, 0, 0, 0.33)",
},

".ace-katzenmilch .ace_marker-layer .ace_active-line": {
	backgroundColor: "rgb(232, 242, 254)",
},

".ace-katzenmilch .ace_gutter-active-line": {
	backgroundColor: "rgb(232, 242, 254)",
},

".ace-katzenmilch .ace_marker-layer .ace_selected-word": {
	border: "1 rgba(100, 5, 208, 0.27)",
},

".ace-katzenmilch .ace_invisible": {
	textColor:"#BFBFBF",
},

".ace-katzenmilch .ace_fold": {
	backgroundColor: "rgba(2, 95, 73, 0.97)",
	borderColor: "rgba(15, 0, 9, 1.0)",
},

".ace-katzenmilch .ace_keyword": {
	textColor: "#674Aa8",
	backgroundColor: "rgba(163, 170, 216, 0.055)",
},

".ace-katzenmilch .ace_constant.ace_language": {
	textColor: "#7D7e52",
	backgroundColor: "rgba(189, 190, 130, 0.059)",
},

".ace-katzenmilch .ace_constant.ace_numeric": {
	textColor:"rgba(79, 130, 123, 0.93)",
	backgroundColor: "rgba(119, 194, 187, 0.059)",
},

".ace-katzenmilch .ace_constant.ace_character,.ace-katzenmilch .ace_constant.ace_other": {
	textColor:"rgba(2, 95, 105, 1.0)",
	backgroundColor: "rgba(127, 34, 153, 0.063)",
},

".ace-katzenmilch .ace_support.ace_function": {
	textColor: "#9D7e62",
	backgroundColor: "rgba(189, 190, 130, 0.039)",
},

".ace-katzenmilch .ace_support.ace_class": {
	textColor:"rgba(239, 106, 167, 1.0)",
	backgroundColor: "rgba(239, 106, 167, 0.063)",
},

".ace-katzenmilch .ace_storage": {
	textColor:"rgba(123, 92, 191, 1.0)",
	backgroundColor: "rgba(139, 93, 223, 0.051)",
},

".ace-katzenmilch .ace_invalid": {
	textColor: "#DFDFD5",
	backgroundColor: "#CC1B27",
},

".ace-katzenmilch .ace_string": {
	textColor: "#5a5f9b",
	backgroundColor: "rgba(170, 175, 219, 0.035)",
},

".ace-katzenmilch .ace_comment": {
	fontSlant: "italic",
	textColor:"rgba(64, 79, 80, 0.67)",
	backgroundColor: "rgba(95, 15, 255, 0.0078)",
},

".ace-katzenmilch .ace_entity.ace_name.ace_function,.ace-katzenmilch .ace_variable": {
	textColor:"rgba(2, 95, 73, 0.97)",
	backgroundColor: "rgba(34, 255, 73, 0.12)",
},

".ace-katzenmilch .ace_variable.ace_language": {
	textColor: "#316fcf",
	backgroundColor: "rgba(58, 175, 255, 0.039)",
},

".ace-katzenmilch .ace_variable.ace_parameter": {
	fontSlant: "italic",
	textColor:"rgba(51, 150, 159, 0.87)",
	backgroundColor: "rgba(5, 214, 249, 0.043)",
},

".ace-katzenmilch .ace_entity.ace_other.ace_attribute-name": {
	textColor:"rgba(73, 70, 194, 0.93)",
	backgroundColor: "rgba(73, 134, 194, 0.035)",
},

".ace-katzenmilch .ace_entity.ace_name.ace_tag": {
	textColor: "#3976a2",
	backgroundColor: "rgba(73, 166, 210, 0.039)",
},

".ace-katzenmilch .ace_indent-guide": {
	// background: "url("data:image/png",base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAACCAYAAACZgbYnAAAAE0lEQVQImWP4////f4bLly//BwAmVgd1/w11/gAAAABJRU5ErkJggg==") right repeat-y;
},

".ace-katzenmilch .ace_indent-guide-active": {
	// background: "url("data:image/png",base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAACCAYAAACZgbYnAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAAAZSURBVHjaYvj///9/hivKyv8BAAAA//8DACLqBhbvk+/eAAAAAElFTkSuQmCC") right repeat-y;
},
});
