import * as dom from "../lib/dom";
dom.importCss({
/* THIS THEME WAS AUTOGENERATED BY Theme.tmpl.css (UUID: "467560D0-6ACE-4409-82FD-4791420837AC) */
".ace-kuroir .ace_gutter": {
	backgroundColor: "#e8e8e8",
	textColor: "#333",
},

".ace-kuroir .ace_print-margin": {
	width: 1,
	backgroundColor: "#e8e8e8",
},

".ace-kuroir": {
	backgroundColor: "#E8E9E8",
	textColor: "#363636",
},

".ace-kuroir .ace_cursor": {
	textColor: "#202020",
},

".ace-kuroir .ace_marker-layer .ace_selection": {
	backgroundColor: "rgba(245, 170, 0, 0.57)",
},

".ace-kuroir.ace_multiselect .ace_selection.ace_start": {
	boxShadow: "0 0 3 #E8E9E8",
},

".ace-kuroir .ace_marker-layer .ace_step": {
	backgroundColor: "rgb(198, 219, 174)",
},

".ace-kuroir .ace_marker-layer .ace_bracket": {
	margin: [-1, 0, 0, -1],
	border: "1 rgba(0, 0, 0, 0.29)",
},

".ace-kuroir .ace_marker-layer .ace_active-line": {
	backgroundColor: "rgba(203, 220, 47, 0.22)",
},

".ace-kuroir .ace_gutter-active-line": {
	backgroundColor: "rgba(203, 220, 47, 0.22)",
},

".ace-kuroir .ace_marker-layer .ace_selected-word": {
	border: "1 rgba(245, 170, 0, 0.57)",
},

".ace-kuroir .ace_invisible": {
	textColor:"#BFBFBF",
},

".ace-kuroir .ace_fold": {
	borderColor: "#363636",
},

".ace-kuroir .ace_constant":  {textColor: "#CD6839",},

".ace-kuroir .ace_constant.ace_numeric": {textColor: "#9A5925",},

".ace-kuroir .ace_support": {textColor: "#104E8B",},
".ace-kuroir .ace_support.ace_function": {textColor: "#005273",},
".ace-kuroir .ace_support.ace_constant": {textColor: "#CF6A4C",},
".ace-kuroir .ace_storage": {textColor: "#A52A2A",},
".ace-kuroir .ace_invalid.ace_illegal": {textColor: "#FD1224",backgroundColor: "rgba(255, 6, 0, 0.15)",},
".ace-kuroir .ace_invalid.ace_deprecated": {
		// text-decoration: "underline",
textSlant: "italic", textColor: "#FD1732", backgroundColor: "#E8E9E8",},
".ace-kuroir .ace_string": {textColor: "#639300",},
".ace-kuroir .ace_string.ace_regexp": {textColor: "#417E00",backgroundColor: "#C9D4BE",},
".ace-kuroir .ace_comment": {color: "rgba(148, 148, 148, 0.91)",backgroundColor: "rgba(220, 220, 220, 0.56)",},
".ace-kuroir .ace_variable": {textColor: "#009ACD",},
".ace-kuroir .ace_meta.ace_tag": {textColor: "#005273",},
".ace-kuroir .ace_markup.ace_heading": {textColor: "#B8012D",backgroundColor: "rgba(191, 97, 51, 0.051)",},
".ace-kuroir .ace_markup.ace_list": {textColor: "#8F5B26",},

".ace-kuroir .ace_indent-guide": {
	// background: "url("data:image/png",base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAACCAYAAACZgbYnAAAAE0lEQVQImWP4////f4bLly//BwAmVgd1/w11/gAAAABJRU5ErkJggg==") right repeat-y;
},

".ace-kuroir .ace_indent-guide-active": {
	// background: "url("data:image/png",base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAACCAYAAACZgbYnAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAAAZSURBVHjaYvj///9/hivKyv8BAAAA//8DACLqBhbvk+/eAAAAAElFTkSuQmCC") right repeat-y;
} 
});
